### PR TITLE
@task PDA-1475 Confirm the style of Keycloak login option in login page

### PR DESCRIPTION
**Pull request by jchen-parasoft**

### CODE REVIEW

**Comment by yshi-parasoft** [comment]
Everything looks good to me. Except that the color of the button should not be the same with existing sign in button.
Please use color of secondary button for each skin, which is the color of "RESET" button in demo admin page.

**Comment by yshi-parasoft** [comment]
According to Joel's feedback, please move the forgot password link in between the two buttons, more closer to the original sign in button.

**Comment by yshi-parasoft** [comment]
screenshot
Confirmed with Joel about using secondary colors. Also let's follow the wireframe here and please add comment about how large the new background image we need.

**Comment by jchen-parasoft** [comment]
login
I think the height of the new background image should be 430px and the width is same.

**Comment by yshi-parasoft** [comment]
@jchen-parasoft I reviewed the `background-image` we used in aerospace skin and I think we should get rid of this property and use css instead.
For example:
```
border: 1px solid #C2EAFB;
border-radius: 15px;
background: linear-gradient(#3D3D3D, #444444, #434343, #393939, #2E2E2E);
```

**Comment by yshi-parasoft** [comment]
image
The new button should have same button style (except color) as the original button.
Here in the image the new button has border-radius but the original does not.

**Comment by yshi-parasoft** [comment]
I think there are two more `login_border.svg` in the project which can be deleted.

**Pull request merged**
