### PR TITLE
@task PDA-953 Create 49 approvers and 49 purchasers

### PR DESCRIPTION
**Pull request by dtang-parasoft**
- Use 'for' cycle to Create 49 approvers and 49 purchasers

- Test was done

### CODE REVIEW

**Comment by dtang-parasoft** [comment]
Need chengdu team to review first

**Comment by yshi-parasoft** [comment]
Currently when I try to login with "approver2/password" it would fail.
I assume this task should include authentication for the new users.

**Comment by yshi-parasoft** [comment]
image
Please make sure to update the top right corner with correct username.

**Comment by dtang-parasoft** [comment]
> image Please make sure to update the top right corner with correct username.
This is not username,

**Comment by dtang-parasoft** [comment]
> image Please make sure to update the top right corner with correct username.
This is not username,

**Comment by dtang-parasoft** [comment]
We can discuss this problem at the next meeting. If changes are needed, we can create some tasks.

**Review by awang-parasoft — APPROVED** [review]

**Comment by yshi-parasoft** [comment]
Ok, seems like the top right corner is displaying the role of the user. I'll approve this and maybe later we can think about adding a username inside the dropdown.

**Pull request merged**
